# Site settings
name: Jerome Paulraj
title: Jerome Paulraj | Full Stack Software Engineer
description: Architecting dreams using code and clouds.
url: https://jeromegnj.github.io/
baseurl: ''
email: jeromegnj@gmail.com
cover: https://jeromegnj.github.io/img/og.png
logo: https://jeromegnj.github.io/img/emojis/technologist.png
resume: https://jeromegnj.github.io/resume.pdf
social:
  - title: email
    url: mailto:jeromegnj@gmail.com
  - title: whatsapp
    url: https://wa.me/919884149885
  - title: phone
    url: tel:+919884149885  
  - title: x
    url: https://X.com/jeromegnj
  - title: instagram
    url: http://instagram.com/jeromegnj
 # - title: github
  #  url: https://github.com/jeromegnj
  - title: linkedin
    url: https://www.linkedin.com/in/jeromegnj

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
